I have identified a bug in my Code
bnolte$ python listdir.py
<function mongodb_connect at 0x10f2f5398>
Traceback (most recent call last):
  File "listdir.py", line 36, in <module>
    insert_into_database["mongodirectorylist"].insert(dircontents_parsed)
TypeError: 'function' object has no attribute '__getitem__'

Looks like this function "insert_into_database" has an Object "mongodirectorylist" which is completely incorrect. I will have to fix that.