Jsonoutput (#3)
* Midpoint in databaseviajson

* I have identified a bug in my Code

bnolte$ python listdir.py
<function mongodb_connect at 0x10f2f5398>
Traceback (most recent call last):
  File "listdir.py", line 36, in <module>
    insert_into_database["mongodirectorylist"].insert(dircontents_parsed)
TypeError: 'function' object has no attribute '__getitem__'

Looks like this function "insert_into_database" has an Object "mongodirectorylist" which is completely incorrect. I will have to fix that.

* added some print statments to help with debugging. I have also fixed some functions

* Updated the gistofthelist.py to ensure we can commit. First lets make this work

* Converted directories to json and print that.

* Adding debug

* write to collection and returnobjectID ; then query objectID

* I have chosen to add a unique collection for each run.

* Fixed bug for naming unque collection as a string

* Changed source file name to more generic.

* Rename to somthing more reasonable.

* I think i see a better way of creating the joined lists.

* Now functional; Slightly ugly still. Next is to tighten things up